import type { BlockDefinition } from "@repo/editor-core/definitions";
import type { BlockType } from "@repo/editor-core/document";

const renderer = () => null;

export const testBlockDefinitions: Readonly<
  Record<BlockType, BlockDefinition>
> = {
  paragraph: {
    kind: "text",
    rootLayout: "normal",
    type: "paragraph",
    renderer,
    split: { default: "paragraph" },
  },
  heading: {
    kind: "text",
    rootLayout: "normal",
    type: "heading",
    renderer,
    data: { level: 1 },
    split: { default: "paragraph" },
  },
  quote: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "quote",
    renderer,
    content: { required: ["paragraph"] },
    contentBoundary: false,
  },
  code: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "code",
    renderer,
    content: { required: ["paragraph"] },
    contentBoundary: false,
    data: { language: "plaintext" },
  },
  bulletListItem: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "bulletListItem",
    renderer,
    content: { required: ["paragraph"] },
    contentBoundary: false,
  },
  orderedListItem: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "orderedListItem",
    renderer,
    content: { required: ["paragraph"] },
    contentBoundary: false,
  },
  checklistItem: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "checklistItem",
    renderer,
    content: { required: ["paragraph"] },
    contentBoundary: false,
    data: { checked: false },
  },
  placeholder: {
    kind: "atomic",
    rootLayout: "normal",
    type: "placeholder",
    renderer,
  },
  divider: { kind: "atomic", rootLayout: "normal", type: "divider", renderer },
  image: {
    kind: "atomic",
    rootLayout: "normal",
    type: "image",
    renderer,
    data: { src: "" },
  },
  video: {
    kind: "atomic",
    rootLayout: "normal",
    type: "video",
    renderer,
    data: { src: "" },
  },
  audio: {
    kind: "atomic",
    rootLayout: "normal",
    type: "audio",
    renderer,
    data: { src: "" },
  },
  file: {
    kind: "atomic",
    rootLayout: "normal",
    type: "file",
    renderer,
    data: { fileId: "" },
  },
  embed: {
    kind: "atomic",
    rootLayout: "normal",
    type: "embed",
    renderer,
    data: { url: "" },
  },
  canvas: {
    kind: "atomic",
    rootLayout: "full",
    type: "canvas",
    renderer,
    data: { width: 0 },
  },
  database: {
    kind: "atomic",
    rootLayout: "full",
    type: "database",
    renderer,
    data: { width: 0, viewId: "" },
  },
  callout: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "callout",
    renderer,
    content: { required: ["block"], additional: "block" },
    contentBoundary: false,
    defaultContent: "paragraph",
  },
  toggleHeading: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "toggleHeading",
    renderer,
    content: { required: ["heading", "toggleHeadingBody"] },
    contentBoundary: false,
  },
  toggleHeadingBody: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "toggleHeadingBody",
    renderer,
    content: { required: ["block"], additional: "block" },
    contentBoundary: false,
    defaultContent: "placeholder",
  },
  toggleListItem: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "toggleListItem",
    renderer,
    content: { required: ["paragraph", "toggleListItemBody"] },
    contentBoundary: false,
  },
  toggleListItemBody: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "toggleListItemBody",
    renderer,
    content: { required: ["block"], additional: "block" },
    contentBoundary: false,
    defaultContent: "placeholder",
  },
  columns: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "columns",
    renderer,
    content: { required: ["column"], additional: "column" },
    contentBoundary: false,
    defaultContent: "column",
  },
  column: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "column",
    renderer,
    content: { required: ["block"], additional: "block" },
    contentBoundary: true,
    defaultContent: "paragraph",
  },
  tabs: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "tabs",
    renderer,
    content: { required: ["tabPane"], additional: "tabPane" },
    contentBoundary: false,
    defaultContent: "tabPane",
  },
  tabPane: {
    kind: "wrapper",
    rootLayout: "normal",
    type: "tabPane",
    renderer,
    content: { required: ["block"], additional: "block" },
    contentBoundary: false,
    defaultContent: "placeholder",
  },
};
